### PR TITLE
Add express and a SSR component for chat display

### PR DESCRIPTION
**Pull request by alexgQQ**
This is an attempt at introducing browser sourcing capabilities for OBS by exposing a server rendered component alongside the electron application with express.

The main issue is data handling between the electron process and the server process. This impacts the actual phrases being sent and configuration settings for the display. I think a simple redux setup can be a good fix for this for exchanging that data.

During some work on this I also read some issue chatter around performance and production build issues with running an express server on an electron main process. Will need to investigate this a bit further.

So far this can be tested from this branch, just `yarn && yarn build:server && yarn start` then use http://localhost:3000/ to view.

TODOS:
- [x] Fix audio playback on server render (need to build audio assets with express)
- [x] Fix import errors on universal-emoji-parser
- [x] Handle phrases from electron app to the server component
- [x] Update settings storage to passthrough to server component
- [x] Cleanup webpack configuration
- [x] Investigate possible production build issues

### CODE REVIEW

**Comment by alexgQQ** [comment]
Did some more work on this. There are definitely some webpack issues to sort out with this config for cleanup and production issues. Trying to bundle the server components for a production distro on my machines fails. The current emoji parser also fails to install for the display bundle due to the web target.

**Comment by Y0dax** [comment]
I'll be following this and contributing if I have time. This is great that you were able to get a prototype local server running.

**Comment by alexgQQ** [comment]
Worked through a few things on this, but I think this is a good starting point to iterate from.

- Ran through some perf test across linux and windows builds. Didn't observe some expected performance issues with the express server.
- The client bundle is targeted for browser environments and has trouble building external libraries requiring direct static files. This was problematic for emoji support as the base library and the [twitch ](https://github.com/mkody/twitch-emoticons) emote libraries rely on these. We may need to use a pattern to proxy them from the express server as that node env can handle them.
- I mentioned using redux but found it more convenient to use the already present express server for sending display configs. I couldn't find a good reason to use redux apart from it being cool, so I left it out for now.

**Comment by Y0dax** [comment]
PR replaced by https://github.com/Y0dax/Oratio/pull/129

**Pull request closed without merging**
